# Generated by Django 4.2.4 on 2023-09-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabmanagement', '0001_initial'),
        ('tripmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user_manyfield',
            field=models.ManyToManyField(to='cabmanagement.userinfo'),
        ),
    ]
